### ISSUE TITLE
How to get response headers

### ISSUE THREAD

**Issue by vslinko** [ded/reqwest#134]
`success` callback provides only parsed response body, but not raw response.
How I can read `Link` response headers, for example?

**Comment by thom-nic** [comment]
This actually tripped me up because I was expecting the `success` handler to follow jQuery.  Good to see there's a workaround.  Would be nice to have this documented in the README as an API difference  from jQuery.

That said, why not pass a `status` and `xhr` arguments to callbacks like JQ does?  IMO it's cleaner than having to grab a reference to the returned request object as described.  A change to here wouldn't even affect current reqwest users.

**Comment by JMacLulich** [comment]
I have to say this is a very very awkward solution to something that should be supplied as callback arguments. Anything on the horizon on supporting this in a logical manner?

**Comment by boazhachlili** [comment]
+1

**Comment by rafaelosoto** [comment]
+1

**Comment by Globegitter** [comment]
Yep, that just tripped me up as well and makes our implementation much more tricky.

**Comment by jordanstephens** [comment]
Just want to add my voice to the ring. This is indeed an awkward implementation.

**Comment by MathieuCh** [comment]
+1

**Comment by marcelhageman** [comment]
+1

**Comment by crismali** [comment]
+1

**Comment by bbtx0** [comment]
+1

**Comment by fpruitt** [comment]
+1

**Comment by squll1** [comment]
+1

**Comment by ifritNkylin** [comment]
here‘s  the way to get all response header names :

console.log(r.request.getAllResponseHeaders())
